# Stage 1: 
FROM node:18-alpine as frontend-build

WORKDIR /app

COPY ./frontend/package*.json ./frontend/
RUN npm install --prefix ./frontend

COPY ./frontend ./frontend
RUN npm run build --prefix ./frontend

# Stage 2: 
FROM node:18-alpine

WORKDIR /app

COPY ./package*.json ./
RUN npm install

COPY ./backend ./backend

# Copy the built frontend from Stage 1
COPY --from=frontend-build /app/frontend/dist ./frontend/dist

# Set environment variables
ENV NODE_ENV=production
ENV PORT=5000

# Expose the application's port
EXPOSE 5000

# Command to start the application
CMD ["npm", "start"]
